-- Enable RLS
alter default privileges in schema public grant all on tables to postgres, service_role;

-- 1. Regions Table
create table regions (
  id bigint generated by default as identity primary key,
  name text not null,
  user_id uuid references auth.users not null default auth.uid(),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table regions enable row level security;

create policy "Users can view their own regions"
  on regions for select
  using (auth.uid() = user_id);

create policy "Users can insert their own regions"
  on regions for insert
  with check (auth.uid() = user_id);

create policy "Users can delete their own regions"
  on regions for delete
  using (auth.uid() = user_id);

-- 2. Products Table
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  user_id uuid references auth.users not null default auth.uid(),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table products enable row level security;

create policy "Users can view their own products"
  on products for select
  using (auth.uid() = user_id);

create policy "Users can insert their own products"
  on products for insert
  with check (auth.uid() = user_id);

create policy "Users can delete their own products"
  on products for delete
  using (auth.uid() = user_id);

-- 3. Stores Table
create table stores (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  seller_name text,
  address text,
  phone text,
  region text, -- storing region name directly for simplicity as per original app, or could be FK
  ideal_time text,
  purchase_prob text,
  visit_days integer[], -- Array of integers 0-6
  visited boolean default false,
  user_id uuid references auth.users not null default auth.uid(),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table stores enable row level security;

create policy "Users can view their own stores"
  on stores for select
  using (auth.uid() = user_id);

create policy "Users can insert their own stores"
  on stores for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own stores"
  on stores for update
  using (auth.uid() = user_id);

create policy "Users can delete their own stores"
  on stores for delete
  using (auth.uid() = user_id);

-- 4. Orders Table
create table orders (
  id bigint generated by default as identity primary key,
  store_id bigint references stores(id) on delete cascade,
  date text not null, -- Storing as Persian date string or ISO? Original app uses Persian string. Let's keep text for simplicity or ISO date.
  -- Actually, standard practice is ISO date, but app logic uses Persian. Let's store text to avoid conversion headaches for now.
  text text,
  items jsonb, -- Storing items as JSON array: [{productId, productName, count}, ...]
  user_id uuid references auth.users not null default auth.uid(),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table orders enable row level security;

create policy "Users can view their own orders"
  on orders for select
  using (auth.uid() = user_id);

create policy "Users can insert their own orders"
  on orders for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own orders"
  on orders for update
  using (auth.uid() = user_id);

create policy "Users can delete their own orders"
  on orders for delete
  using (auth.uid() = user_id);
