-- Enable RLS
alter default privileges in schema public grant all on tables to postgres, service_role;

-- 1. Add last_visit to stores if not exists
alter table stores add column if not exists last_visit timestamp with time zone;

-- 2. Create visit_logs table
create table if not exists visit_logs (
  id bigint generated by default as identity primary key,
  store_id bigint references stores(id) on delete cascade,
  visited_at timestamp with time zone default timezone('utc'::text, now()) not null,
  note text, -- Added for descriptions
  user_id uuid references auth.users not null default auth.uid(),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table visit_logs enable row level security;

-- Add 'note' column if it doesn't exist (for existing tables)
alter table visit_logs add column if not exists note text;

drop policy if exists "Users can view their own visit_logs" on visit_logs;
drop policy if exists "Users can insert their own visit_logs" on visit_logs;
drop policy if exists "Users can update their own visit_logs" on visit_logs;
drop policy if exists "Users can delete their own visit_logs" on visit_logs;

create policy "Users can view their own visit_logs"
  on visit_logs for select
  using (auth.uid() = user_id);

create policy "Users can insert their own visit_logs"
  on visit_logs for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own visit_logs"
  on visit_logs for update
  using (auth.uid() = user_id);

create policy "Users can delete their own visit_logs"
  on visit_logs for delete
  using (auth.uid() = user_id);

-- 3. Visits Table (Existing Appointments)
create table if not exists visits (
  id bigint generated by default as identity primary key,
  store_id bigint references stores(id) on delete cascade,
  visit_date text not null, -- Storing as Persian date string YYYY/MM/DD
  visit_time text, -- HH:MM
  note text,
  status text default 'pending', -- pending, done
  user_id uuid references auth.users not null default auth.uid(),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table visits enable row level security;

drop policy if exists "Users can view their own visits" on visits;
drop policy if exists "Users can insert their own visits" on visits;
drop policy if exists "Users can update their own visits" on visits;
drop policy if exists "Users can delete their own visits" on visits;

create policy "Users can view their own visits"
  on visits for select
  using (auth.uid() = user_id);

create policy "Users can insert their own visits"
  on visits for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own visits"
  on visits for update
  using (auth.uid() = user_id);

create policy "Users can delete their own visits"
  on visits for delete
  using (auth.uid() = user_id);
