-- Add Visits Table
create table visits (
  id bigint generated by default as identity primary key,
  store_id bigint references stores(id) on delete cascade,
  visit_date text not null, -- Storing as Persian date string YYYY/MM/DD
  visit_time text, -- HH:MM
  note text,
  status text default 'pending', -- pending, done
  user_id uuid references auth.users not null default auth.uid(),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table visits enable row level security;

create policy "Users can view their own visits"
  on visits for select
  using (auth.uid() = user_id);

create policy "Users can insert their own visits"
  on visits for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own visits"
  on visits for update
  using (auth.uid() = user_id);

create policy "Users can delete their own visits"
  on visits for delete
  using (auth.uid() = user_id);
