import { Toast } from '../shared/Toast.js';

export const SettingsModal = {
    initListeners() {
        document.getElementById('settingsModal').addEventListener('show.bs.modal', () => this.loadTelegramSettings());
        document.getElementById('saveTelegramSettingsBtn').addEventListener('click', () => this.saveTelegramSettings());

        document.getElementById('showDbScriptBtn').addEventListener('click', () => this.showSqlModal());
        document.getElementById('copySqlBtn').addEventListener('click', () => {
             const textarea = document.getElementById('sqlContent');
             textarea.select();
             navigator.clipboard.writeText(textarea.value);
             Toast.show('کپی شد', 'success');
        });
    },

    loadTelegramSettings() {
        const token = localStorage.getItem('bolt_telegram_token') || '';
        const userId = localStorage.getItem('bolt_telegram_userid') || '';
        document.getElementById('telegramBotToken').value = token;
        document.getElementById('telegramUserId').value = userId;
    },

    saveTelegramSettings() {
        const token = document.getElementById('telegramBotToken').value.trim();
        const userId = document.getElementById('telegramUserId').value.trim();

        localStorage.setItem('bolt_telegram_token', token);
        localStorage.setItem('bolt_telegram_userid', userId);

        Toast.show('تنظیمات تلگرام ذخیره شد.', 'success');
    },

    showSqlModal() {
        const sql = `-- Enable RLS
alter default privileges in schema public grant all on tables to postgres, service_role;

-- 1. Regions
create table if not exists regions (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table regions enable row level security;
drop policy if exists "Public regions" on regions;
create policy "Public regions" on regions for all using (true);

-- 2. Products
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table products enable row level security;
drop policy if exists "Public products" on products;
create policy "Public products" on products for all using (true);

-- 3. Stores
create table if not exists stores (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  seller_name text,
  address text,
  phone text,
  region text,
  ideal_time text,
  purchase_prob text,
  visit_days int[],
  visited boolean default false,
  last_visit timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table stores enable row level security;
drop policy if exists "Public stores" on stores;
create policy "Public stores" on stores for all using (true);

-- 4. Orders
create table if not exists orders (
  id bigint generated by default as identity primary key,
  store_id bigint references stores(id) on delete cascade,
  date text,
  text text,
  items jsonb,
  user_id uuid references auth.users default auth.uid(),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table orders enable row level security;
drop policy if exists "Public orders" on orders;
create policy "Public orders" on orders for all using (true);

-- 5. Visits (Appointments)
create table if not exists visits (
  id bigint generated by default as identity primary key,
  store_id bigint references stores(id) on delete cascade,
  visit_date text not null,
  visit_time text,
  note text,
  status text default 'pending',
  user_id uuid references auth.users default auth.uid(),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table visits enable row level security;
drop policy if exists "Public visits" on visits;
create policy "Public visits" on visits for all using (true);

-- 6. Visit Logs (History)
create table if not exists visit_logs (
  id bigint generated by default as identity primary key,
  store_id bigint references stores(id) on delete cascade,
  visited_at timestamp with time zone default timezone('utc'::text, now()) not null,
  note text,
  visit_type text default 'physical'
);
alter table visit_logs enable row level security;
drop policy if exists "Public visit_logs" on visit_logs;
create policy "Public visit_logs" on visit_logs for all using (true);

-- Indexes
create index if not exists idx_stores_region on stores(region);
create index if not exists idx_visit_logs_store_id on visit_logs(store_id);
`;
        document.getElementById('sqlContent').value = sql;
        new bootstrap.Modal(document.getElementById('sqlModal')).show();
    }
};
