import { Toast } from '../shared/Toast.js';

export const SettingsModal = {
    initListeners() {
        document.getElementById('settingsModal').addEventListener('show.bs.modal', () => this.loadTelegramSettings());
        document.getElementById('saveTelegramSettingsBtn').addEventListener('click', () => this.saveTelegramSettings());

        document.getElementById('showDbScriptBtn').addEventListener('click', () => this.showSqlModal());
        document.getElementById('copySqlBtn').addEventListener('click', () => {
             const textarea = document.getElementById('sqlContent');
             textarea.select();
             navigator.clipboard.writeText(textarea.value);
             Toast.show('کپی شد', 'success');
        });
    },

    loadTelegramSettings() {
        const token = localStorage.getItem('bolt_telegram_token') || '';
        const userId = localStorage.getItem('bolt_telegram_userid') || '';
        document.getElementById('telegramBotToken').value = token;
        document.getElementById('telegramUserId').value = userId;
    },

    saveTelegramSettings() {
        const token = document.getElementById('telegramBotToken').value.trim();
        const userId = document.getElementById('telegramUserId').value.trim();

        localStorage.setItem('bolt_telegram_token', token);
        localStorage.setItem('bolt_telegram_userid', userId);

        Toast.show('تنظیمات تلگرام ذخیره شد.', 'success');
    },

    showSqlModal() {
        const sql = `-- Enable RLS
alter default privileges in schema public grant all on tables to postgres, service_role;

-- Visits Table
create table if not exists visits (
  id bigint generated by default as identity primary key,
  store_id bigint references stores(id) on delete cascade,
  visit_date text not null,
  visit_time text,
  note text,
  status text default 'pending',
  user_id uuid references auth.users not null default auth.uid(),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table visits enable row level security;

create policy "Users can view their own visits"
  on visits for select
  using (auth.uid() = user_id);

create policy "Users can insert their own visits"
  on visits for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own visits"
  on visits for update
  using (auth.uid() = user_id);

create policy "Users can delete their own visits"
  on visits for delete
  using (auth.uid() = user_id);
`;
        document.getElementById('sqlContent').value = sql;
        new bootstrap.Modal(document.getElementById('sqlModal')).show();
    }
};
